# ExternalSecret for the azure.json config file.
# Pulls the JSON blob from Key Vault (written by tofu) and
# creates the secret that ExternalDNS mounts at /etc/kubernetes/.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-config-file
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ng6-external-dns
    kind: ClusterSecretStore
  target:
    name: azure-config-file
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: azure.json
      remoteRef:
        key: external-dns-azure-config
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
