external-dns:
  provider:
    name: azure
  txtOwnerId: infra-aks-new
  policy: sync
  sources:
    - crd
    - gateway-httproute
    - gateway-grpcroute
    - gateway-tcproute
    - gateway-tlsroute
  extraArgs:
    crd-source-apiversion: externaldns.k8s.io/v1alpha1
    crd-source-kind: DNSEndpoint
  rbac:
    additionalPermissions:
      - apiGroups: ["externaldns.k8s.io"]
        resources: ["dnsendpoints"]
        verbs: ["get", "watch", "list"]
      - apiGroups: ["externaldns.k8s.io"]
        resources: ["dnsendpoints/status"]
        verbs: ["*"]
  serviceAccount:
    annotations:
      azure.workload.identity/client-id: 44b0ff37-b886-4101-ab19-23388ead9c0b
  podLabels:
    azure.workload.identity/use: "true"
  domainFilters:
    - romaine.life
  extraVolumes:
    - name: azure-config
      secret:
        secretName: azure-config-file
  extraVolumeMounts:
    - name: azure-config
      mountPath: /etc/kubernetes
      readOnly: true
