grafana:
  replicas: 1

  persistence:
    enabled: true
    type: pvc
    storageClassName: managed-csi
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi

  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  grafana.ini:
    server:
      domain: grafana.romaine.life
      root_url: https://grafana.romaine.life/
    analytics:
      reporting_enabled: false
      check_for_updates: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.loki.svc.cluster.local
          isDefault: true
          jsonData:
            maxLines: 1000

  testFramework:
    enabled: false
