apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: ng6-argocd
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://ng6-argocd.vault.azure.net/
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
